# This are the machine-independent bashrc settings
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias sl='ls'
alias LS='ls'
alias ls='ls -lAH'
alias ipython='ipython --TerminalInteractiveShell.editing_mode=vi'
alias elcs='export SIMPLE_SETTINGS=src.countryside_search.settings.local'
alias elc='export SIMPLE_SETTINGS=src.countryside.settings.local'
alias et='export SIMPLE_SETTINGS=tests.settings'
